/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-18 06:12:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671504870577L));
    _jspx_dependants.put("jar:file:/C:/Users/ezen/Desktop/최신/book1-main%20(1)/book1-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/book/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/92e616dfba.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/memberJoin.js\"></script>\n");
      out.write("<link href=\"/resources/css/memberJoin.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".pwRe_ok {\n");
      out.write("	color: #008000;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pwRe_rewrite {\n");
      out.write("	color: #ff0000;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pwRe_null {\n");
      out.write("	color: #ff0000;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<form action=\"/mem/join\" method=\"post\">\n");
      out.write("		<div class=\"join-container\">\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<a href=\"/\"><img src=\"../resources/img/logo.jpg\" alt=\"로고\"></a><br>\n");
      out.write("			</div>\n");
      out.write("			<lable for=\"mem_id\">ID</lable>\n");
      out.write("			<br> <input type=\"text\" class=\"join-input\" name=\"mem_id\" id=\"mem_id\" placeholder=\"아이디\" onchange=\"checkId()\" required> <span class=\"id_ok\"><i class=\"fa-solid fa-check\"></i></span> <span class=\"id_duplicate\"><i class=\"fa-solid fa-x\"></i></span> <span class=\"id_null\"><i class=\"fa-solid fa-x\"></i></span> <Br>\n");
      out.write("			<lable for=\"mem_pw\">PW</lable>\n");
      out.write("			<br> <input type=\"password\" class=\"join-input\" name=\"mem_pw\" id=\"mem_pw\" placeholder=\"영문(대소문자 구분X), 숫자, 특수문자 조합, 9~12자리\" onchange=\"checkPw()\" required> \n");
      out.write("				<span class=\"pw_ok\"><i class=\"fa-solid fa-check\"></i></span> \n");
      out.write("				<span class=\"pw_rewrite\"><i class=\"fa-solid fa-x\"></i></span> \n");
      out.write("				<span class=\"pw_null\"><i class=\"fa-solid fa-x\"></i></span><br>\n");
      out.write("\n");
      out.write("			<lable for=\"mem_pwRe\">PW Re</lable>\n");
      out.write("			<br> <input type=\"password\" class=\"join-input\" name=\"mem_pwRe\" id=\"mem_pwRe\" placeholder=\"비밀번호 확인을 위해 한번 더 입력해주세요\" onchange=\"checkPwRe()\" required> \n");
      out.write("				<span class=\"pwRe_ok\"><i class=\"fa-solid fa-check\"></i></span> \n");
      out.write("				<span class=\"pwRe_rewrite\"><i class=\"fa-solid fa-x\"></i></span> \n");
      out.write("				<span class=\"pwRe_null\"><i class=\"fa-solid fa-x\"></i></span> <br>\n");
      out.write("\n");
      out.write("			<lable for=\"mem_name\">NAME</lable>\n");
      out.write("			<br> <input type=\"text\" class=\"join-input\" name=\"mem_name\" placeholder=\"이름\" required> <br>\n");
      out.write("			<lable for=\"mem_postzip\">ADDRESS</lable>\n");
      out.write("			<br> <input type=\"text\" class=\"join-input zip\" id=\"postcode\" name=\"mem_postzip\" placeholder=\"우편번호\" required> <input type=\"button\" class=\"join-input zip btn btn-outline-primary\" onclick=\"execDaumPostcode()\" value=\"우편번호 찾기\"> <br> <input type=\"text\" class=\"join-input\" id=\"address\" name=\"address\" placeholder=\"주소\" required> <br> <input type=\"text\" class=\"join-input\" id=\"detailAddress\" name=\"detailAddress\" placeholder=\"상세주소\" required> <input type=\"text\" class=\"join-input\" id=\"extraAddress\" name=\"extraAddress\" placeholder=\"참고항목\" readonly=\"readonly\"> <br>\n");
      out.write("			<lable for=\"mem_age\">AGE</lable>\n");
      out.write("			<br> <input type=\"text\" class=\"join-input\" name=\"mem_age\" placeholder=\"나이\" required> <br>\n");
      out.write("			<lable for=\"mem_gender\">GENDER</lable>\n");
      out.write("			<br> <select class=\"join-input\" name=\"mem_gender\">\n");
      out.write("\n");
      out.write("				<option value=\"0\">남자</option>\n");
      out.write("				<option value=\"1\">여자</option>\n");
      out.write("			</select> <br>\n");
      out.write("			<lable for=\"mem_cell_num\">PHONE</lable>\n");
      out.write("			<br> <input type=\"text\" class=\"join-input\" name=\"mem_cell_num\" id=\"mem_cell_num\" placeholder=\"숫자만 써주세요\" onchange=\"checkCellNum()\" required> \n");
      out.write("				<span class=\"cellNum_ok\"><i class=\"fa-solid fa-check\"></i></span> \n");
      out.write("				<span class=\"cellNum_duplicate\"><i class=\"fa-solid fa-x\"></i></span> \n");
      out.write("				<span class=\"cellNum_null\"><i class=\"fa-solid fa-x\"></i></span> <br>\n");
      out.write("			<lable for=\"mem_cno\">FAVORITE</lable>\n");
      out.write("			<br> <select class=\"join-input\" name=\"mem_cno\">\n");
      out.write("\n");
      out.write("				<option value=\"novel\">소설</option>\n");
      out.write("				<option value=\"essay\">에세이</option>\n");
      out.write("				<option value=\"life\">건강/취미</option>\n");
      out.write("				<option value=\"computer\">컴퓨터/모바일</option>\n");
      out.write("				<option value=\"problem\">문제집</option>\n");
      out.write("			</select> <Br>\n");
      out.write("			<button type=submit \" class=\"btn btn-outline-secondary btn-submit\">가입하기</button>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<p>\n");
      out.write("			이미 가입되어 있으신가요? <a href=\"/mem/loginPage\">로그인하기</a>\n");
      out.write("		</p>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
